tasks:
  - name: terraform
    before: |
      source ./bin/create_tfrc_cred.sh
      source ./bin/install_terraform_cli.sh 
      source ./bin/add_tf_alias.sh
      source ~/.bash_profile
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli.sh
      source ./bin/add_tf_alias.sh
      source ~/.bash_profile

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
